# -*- coding: utf-8 -*-
"""requests

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/107moZIwOXGx_ymAMf6OYekuv0z21jUj1
"""

import requests

r = requests.get('https://colab.research.google.com/drive/1wMBOzwh7XUq-Yg_Yiz0hxzdzclnZ1bGk#scrollTo=gdCwQZkkY4V8&line=15&uniqifier=1')

with open('weather.text','wb') as a:
  a.write(r.content)